"""Design Bible Chapter 70 Part 1 — Executive Board & CEO Intelligence
System. BoardRoster is computed fresh per request (see app/board.py's
module docstring — the same convention app/situation_room.py already
established for a cross-cutting, read-only aggregate). BoardReport is
real, persisted history — generated by app/nexus.py on its own daily/
quarterly/emergency cadence, this endpoint only ever reads it back.
"""
from __future__ import annotations

from datetime import datetime, timezone

from fastapi import APIRouter

from app.board import compute_board_roster
from app.schemas import BoardReport, BoardRoster
from app.state import game_state

router = APIRouter(prefix="/api/board", tags=["board"])


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


@router.get("/roster", response_model=BoardRoster)
async def get_board_roster() -> BoardRoster:
    return compute_board_roster(now_iso=_now_iso())


@router.get("/reports", response_model=list[BoardReport])
async def get_board_reports() -> list[BoardReport]:
    state = await game_state.snapshot()
    return state.board_reports
