"""app/walk_forward.py — CEO directive "Professional Quant Trading Firm
— Quant Intelligence + Market Analysis Completion Phase (Next Research +
Validation Pass)," item 4: genuine walk-forward validation over real,
sequential, chronological candle history.

RESEARCH FIRST. app/model_validation.py's `_temporal_stability_check`
already exists and is honestly labeled a "Walk-Forward / Temporal-Split
Validation... analog" — but it splits a LIST OF PAST `SimulationResult`
RUNS (whole-run aggregate outcomes, mostly RNG-generated by
app/simulation.py) into exactly two chronological halves. It is not, and
never claimed to be, a real bar-level walk-forward over sequential price
history — its own docstring says so plainly. This module is a
genuinely different, NEW capability, made architecturally possible only
because app/strategy_engine.py (CEO directive "...Quant Intelligence +
Market Analysis Completion Phase," Phase F) already produces a real,
deterministic, bar-by-bar backtest over a real chronological (mock)
candle series for an arbitrary compiled strategy. `_temporal_stability_
check` is untouched and still real — this module does not replace it,
since it validates a different, complementary thing (cross-STRATEGY-RUN
stability vs. this module's within-one-definition, real bar-level
stability).

ONE AUTHORITATIVE IMPLEMENTATION. Every window below is backtested via
app/strategy_engine.py's own `backtest_symbol_over_candles()` — the
EXACT SAME setup-detection/stop-resolution/exit-simulation pipeline
`run_compiled_strategy_backtest()` uses on the full series, just handed
a real, disjoint chronological SUB-SLICE of `Candle` objects instead.
This is what makes the no-look-ahead guarantee structural rather than a
convention a caller has to remember: `backtest_symbol_over_candles()`
has no notion of "the rest of the series" at all — a call with
`candles[2000:3000]` can only ever resolve an indicator or detect a
setup using bars 2000-2999. Bucket aggregation reuses
app/backtest_primitives.py's `aggregate_bucket()` directly — never a
second aggregation formula.

WHAT THIS DOES: consecutive, NON-OVERLAPPING windows of `window_bars`
real bars each (window 1 = bars[0:window_bars], window 2 =
bars[window_bars:2*window_bars], ...) — a real, disjoint chronological
walk forward. A trailing partial window (fewer than `window_bars` real
bars left) is dropped rather than backtested as if it were a full window
— an incomplete window would understate real setup opportunity, not a
fair comparison against the others.

WHAT THIS DELIBERATELY DOES NOT DO (a real, disclosed scope cut, not a
gap papered over): no per-window parameter re-selection. This module
tests whether ONE FIXED compiled definition's own edge holds up
window after window (walk-forward STABILITY), not whether re-optimizing
a parameter each window would have done better (walk-forward
OPTIMIZATION) — see app/parameter_sensitivity.py for this same
directive's separate, disjoint parameter-robustness sweep over the FULL
series. Nesting the two into nested nested walk-forward-with-
reoptimization is real, tractable future work, not attempted here.

`verdict` is computed from real, disclosed thresholds
(`MIN_EVALUATED_WINDOWS_FOR_VERDICT`, `STABLE_POSITIVE_WINDOW_FRACTION`)
over every real window that had enough closed trades for its own bucket-
level verdict (`EmaPullbackStatsBucket.verdict == "enough_evidence"`) —
never a forced call from too few windows, and every individual window's
own real numbers are always returned alongside the verdict, never
hidden behind it.
"""
from __future__ import annotations

from datetime import datetime, timezone

from app.backtest_primitives import aggregate_bucket
from app.market_data import market_data_provider
from app.schemas import CompiledStrategyDefinition, WalkForwardSymbolResult, WalkForwardValidationResult, WalkForwardWindowResult
from app.strategy_engine import DEFAULT_CANDLES_PER_SYMBOL, DEFAULT_TIMEFRAME, MAX_HOLD_BARS, MIN_BARS_ON_SIDE_BEFORE_CROSS, _unsupported_indicators, backtest_symbol_over_candles
from app.watchlist import SEED_SYMBOLS

DEFAULT_WINDOW_BARS = 1000
MIN_EVALUATED_WINDOWS_FOR_VERDICT = 3
STABLE_POSITIVE_WINDOW_FRACTION = 0.6

DATA_HONESTY_NOTE = (
    "Every candle in every window is app/market_data.py's own real, procedurally-generated (seeded, reproducible) "
    "mock OHLCV series — never real historical market data. Each window is backtested in complete isolation from "
    "every other window (a real, disjoint chronological slice, never sharing indicator state across window "
    "boundaries) — the real structural guarantee no signal in one window ever saw a candle from another."
)


def run_walk_forward_validation(
    definition: CompiledStrategyDefinition,
    *,
    symbols: list[str] | None = None,
    timeframe: str = DEFAULT_TIMEFRAME,
    candles_per_symbol: int = DEFAULT_CANDLES_PER_SYMBOL,
    window_bars: int = DEFAULT_WINDOW_BARS,
) -> WalkForwardValidationResult:
    """The one real entry point. Refuses (clear, honest reason in
    `detail`, an empty `symbols` list) exactly when
    `run_compiled_strategy_backtest()` would — an unresolved definition
    or an indicator this engine's v1 scope cannot resolve — never a
    silently-guessed partial result."""
    now_iso = datetime.now(timezone.utc).isoformat()
    test_symbols = symbols if symbols is not None else [s for s, _name, _cat in SEED_SYMBOLS]
    result_id = f"walk-forward-{definition.id}-{window_bars}"

    def _refusal(reason: str) -> WalkForwardValidationResult:
        return WalkForwardValidationResult(
            id=result_id,
            definitionId=definition.id,
            definitionVersion=definition.version,
            windowBars=window_bars,
            symbols=[],
            verdict="insufficient_data",
            detail=reason,
            dataHonestyNote=DATA_HONESTY_NOTE,
            generatedAt=now_iso,
        )

    if definition.status != "compiled":
        return _refusal(f"This definition is not backtestable: status={definition.status!r}. {definition.detail}")
    unsupported = _unsupported_indicators(definition)
    if unsupported:
        return _refusal(f"This engine's current v1 scope cannot resolve indicator(s) {sorted(unsupported)} — a real, disclosed coverage gap, not a fabricated result.")
    if window_bars < MIN_BARS_ON_SIDE_BEFORE_CROSS + MAX_HOLD_BARS + 60:
        return _refusal(f"window_bars={window_bars} is too small to ever produce a real setup — needs at least {MIN_BARS_ON_SIDE_BEFORE_CROSS + MAX_HOLD_BARS + 60} real bars.")

    symbol_results: list[WalkForwardSymbolResult] = []
    for symbol in test_symbols:
        candles = market_data_provider.get_candles(symbol, timeframe, candles_per_symbol)
        windows: list[WalkForwardWindowResult] = []
        window_index = 0
        for start in range(0, len(candles), window_bars):
            window_candles = candles[start : start + window_bars]
            if len(window_candles) < window_bars:
                break  # a real trailing partial window is dropped, never tested as if it were full
            window_index += 1
            trades = backtest_symbol_over_candles(definition, symbol, window_candles)
            bucket = aggregate_bucket(f"window_{window_index}", trades)
            windows.append(
                WalkForwardWindowResult(
                    windowIndex=window_index,
                    startTimestamp=window_candles[0].timestamp,
                    endTimestamp=window_candles[-1].timestamp,
                    bucket=bucket,
                )
            )

        evaluated = [w for w in windows if w.bucket.verdict == "enough_evidence"]
        positive = [w for w in evaluated if w.bucket.expectancy_r is not None and w.bucket.expectancy_r > 0]
        negative = [w for w in evaluated if w.bucket.expectancy_r is not None and w.bucket.expectancy_r <= 0]
        symbol_detail = (
            f"{len(windows)} real window(s) tested, {len(evaluated)} with enough real closed trades for a bucket-level verdict "
            f"({len(positive)} positive expectancy, {len(negative)} non-positive)."
            if windows
            else "Not enough real candle history for even one real window of this size."
        )
        symbol_results.append(
            WalkForwardSymbolResult(
                symbol=symbol,
                windows=windows,
                positiveWindowCount=len(positive),
                negativeWindowCount=len(negative),
                evaluatedWindowCount=len(evaluated),
                detail=symbol_detail,
            )
        )

    total_evaluated = sum(s.evaluated_window_count for s in symbol_results)
    total_positive = sum(s.positive_window_count for s in symbol_results)
    if total_evaluated < MIN_EVALUATED_WINDOWS_FOR_VERDICT:
        verdict: str = "insufficient_data"
        detail = (
            f"Only {total_evaluated} real window(s) across all {len(test_symbols)} symbol(s) had enough closed trades for a bucket-level "
            f"verdict — need at least {MIN_EVALUATED_WINDOWS_FOR_VERDICT} before reading a real stability trend."
        )
    else:
        fraction = total_positive / total_evaluated
        if fraction >= STABLE_POSITIVE_WINDOW_FRACTION:
            verdict = "stable"
            detail = (
                f"{total_positive} of {total_evaluated} real evaluated window(s) ({fraction * 100:.0f}%) show positive expectancy — "
                f"at or above the {STABLE_POSITIVE_WINDOW_FRACTION * 100:g}% bar this module uses for 'stable.'"
            )
        else:
            verdict = "unstable"
            detail = (
                f"Only {total_positive} of {total_evaluated} real evaluated window(s) ({fraction * 100:.0f}%) show positive expectancy — "
                f"below the {STABLE_POSITIVE_WINDOW_FRACTION * 100:g}% bar. This edge does not hold consistently across real, disjoint "
                "chronological windows, whatever the full-series backtest alone reported."
            )

    return WalkForwardValidationResult(
        id=result_id,
        definitionId=definition.id,
        definitionVersion=definition.version,
        windowBars=window_bars,
        symbols=symbol_results,
        verdict=verdict,  # type: ignore[arg-type]
        detail=detail,
        dataHonestyNote=DATA_HONESTY_NOTE,
        generatedAt=now_iso,
    )
