import Phaser from "phaser";
import manifest from "@/assets/manifest.generated.json";

export type AssetKind = "spritesheet" | "tileset" | "static";

export interface ManifestAnimation {
  row: number;
  frameCount: number;
  frameRate: number;
  repeat: number;
}

export interface ManifestAsset {
  id: string;
  category: string;
  sourcePath: string;
  url: string;
  width: number;
  height: number;
  kind?: AssetKind;
  frameWidth?: number;
  frameHeight?: number;
  tileWidth?: number;
  tileHeight?: number;
  animations?: Record<string, ManifestAnimation>;
}

interface GeneratedManifest {
  generatedAt: string;
  assetCount: number;
  assets: Record<string, ManifestAsset>;
}

const typedManifest = manifest as GeneratedManifest;

/**
 * Centralized asset access point. No game code should ever reference an
 * asset file path directly — everything is looked up by id from the
 * manifest generated by scripts/generate-assets.mjs, which discovers files
 * on disk automatically.
 */
export class AssetLoader {
  static get assets(): Record<string, ManifestAsset> {
    return typedManifest.assets;
  }

  static get(id: string): ManifestAsset {
    const asset = typedManifest.assets[id];
    if (!asset) {
      throw new Error(`[AssetLoader] Unknown asset id "${id}". Run "npm run assets:sync" if a new file was added.`);
    }
    return asset;
  }

  static has(id: string): boolean {
    return id in typedManifest.assets;
  }

  static byCategory(category: string): ManifestAsset[] {
    return Object.values(typedManifest.assets).filter((a) => a.category === category);
  }

  /** Queue every manifest asset for loading with the appropriate Phaser loader call. */
  static preloadAll(scene: Phaser.Scene): void {
    for (const asset of Object.values(typedManifest.assets)) {
      AssetLoader.preloadOne(scene, asset);
    }
  }

  static preloadOne(scene: Phaser.Scene, asset: ManifestAsset): void {
    if (scene.textures.exists(asset.id)) return;

    if (asset.kind === "spritesheet" && asset.frameWidth && asset.frameHeight) {
      scene.load.spritesheet(asset.id, asset.url, {
        frameWidth: asset.frameWidth,
        frameHeight: asset.frameHeight,
      });
    } else {
      // Tilesets and static images both load as plain images; tilesets are
      // sliced into frames on demand via textureManager when built into a
      // Phaser tilemap or cropped sprite.
      scene.load.image(asset.id, asset.url);
    }
  }

  /** Build Phaser animations for every manifest asset that declares them. Idempotent. */
  static createAnimations(scene: Phaser.Scene): void {
    for (const asset of Object.values(typedManifest.assets)) {
      if (asset.kind !== "spritesheet" || !asset.animations || !asset.frameWidth) continue;
      const cols = Math.floor(asset.width / asset.frameWidth);

      for (const [animName, def] of Object.entries(asset.animations)) {
        const key = AssetLoader.animKey(asset.id, animName);
        if (scene.anims.exists(key)) continue;
        const start = def.row * cols;
        const end = start + def.frameCount - 1;
        scene.anims.create({
          key,
          frames: scene.anims.generateFrameNumbers(asset.id, { start, end }),
          frameRate: def.frameRate,
          repeat: def.repeat,
        });
      }
    }
  }

  static animKey(assetId: string, animName: string): string {
    return `${assetId}::${animName}`;
  }
}
